In [7]:
#Convert list into array
#importing module
import numpy as np
lst=[23,24,25,26,27]
print(type(lst))
#crete array from list
arr=np.array(lst)
print(type(arr))
arr

<class 'list'>
<class 'numpy.ndarray'>


array([23, 24, 25, 26, 27])

In [13]:
#No. of dimentiion
import numpy as np
arr=np.array([23,24,25,26,27])
print(arr.ndim)

arr=np.array([[23,24,25,26,27],[23,9,89,88,23]])
print(arr.ndim)


1
2


In [14]:
#Shape Function
print(arr.shape)

(2, 5)


In [16]:
#size function
print(arr.size)

10


In [17]:
#dtype function
print(arr.dtype)

int32


In [21]:
#numpy Zero Function
arr=np.zeros([3,3],dtype=None,order='c')
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
#numpy once function
arr=np.ones([2,2],dtype=int)
print(arr)

[[1 1]
 [1 1]]


In [27]:
#Random function
print(np.random.random(3))

print(np.random.random([2,2]))

[0.28924523 0.72929376 0.60338394]
[[0.96572468 0.31985401]
 [0.82454726 0.48418634]]


In [35]:
#arrange- return array with evenly spaced
print(np.arange(3))
print(np.arange(4,50))
print(np.arange(4,50,4))


[0 1 2]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[ 4  8 12 16 20 24 28 32 36 40 44 48]


In [36]:
#linspace function
np.linspace(0.1,0.3,10)

array([0.1       , 0.12222222, 0.14444444, 0.16666667, 0.18888889,
       0.21111111, 0.23333333, 0.25555556, 0.27777778, 0.3       ])

In [50]:
#reshape function
arr=np.array([10,20,3,40,50,60,70,80,90])
print("Column-Wise\n",np.reshape(arr,[3,3],'f'))
print()
print("Row-wise\n",np.reshape(arr,[3,3],'c'))

Column-Wise
 [[10 40 70]
 [20 50 80]
 [ 3 60 90]]

Row-wise
 [[10 20  3]
 [40 50 60]
 [70 80 90]]


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[arr < 5])
arr[arr > 5] = 10
print(arr)

[1 2 3 4]
[ 1  2  3  4  5 10 10 10 10]
